import streamlit as st
import pandas as pd
import numpy as np
import joblib


# --------------------------------------------------
# Page Configuration
# --------------------------------------------------

st.set_page_config(
    page_title="Advertising Sales Predictor",
    page_icon="📊",
    layout="centered"
)


# --------------------------------------------------
# Load Model
# --------------------------------------------------

model = joblib.load("sales_advertising.pkl")


# --------------------------------------------------
# Header
# --------------------------------------------------

st.title("📊 Advertising Sales Predictor")

st.markdown(
    """
    ### Predict Sales Using Advertising Budget

    Enter your advertising budget for **TV, Radio, and Newspaper**
    to predict the expected sales.
    """
)

st.divider()


# --------------------------------------------------
# Input Section
# --------------------------------------------------

st.subheader("📢 Advertising Budget")

col1, col2 = st.columns(2)

with col1:
    tv = st.number_input(
        "📺 TV Advertising",
        min_value=0.0,
        value=100.0,
        step=1.0
    )

with col2:
    radio = st.number_input(
        "📻 Radio Advertising",
        min_value=0.0,
        value=20.0,
        step=1.0
    )

newspaper = st.number_input(
    "📰 Newspaper Advertising",
    min_value=0.0,
    value=30.0,
    step=1.0
)

st.divider()


# --------------------------------------------------
# Prediction
# --------------------------------------------------

if st.button("🔮 Predict Sales", use_container_width=True):

    # Apply the same transformation used during model training
    sqrt_newspaper = np.sqrt(newspaper)

    # Create input DataFrame with the exact feature names
    # expected by the trained model
    input_data = pd.DataFrame({
        "TV": [tv],
        "radio": [radio],
        "sqrt_newspaper": [sqrt_newspaper]
    })

    # Make prediction
    prediction = model.predict(input_data)[0]

    # Display result
    st.success("✅ Prediction completed successfully!")

    st.metric(
        label="📈 Predicted Sales",
        value=f"{prediction:.2f}"
    )

    st.info(
        "The predicted sales value is generated by the trained "
        "machine-learning model."
    )


# --------------------------------------------------
# Footer
# --------------------------------------------------

st.divider()

st.caption(
    "Advertising Sales Prediction System | "
    "Powered by Machine Learning"
)